config/routes.rb
# frozen_string_literal: true

# rubocop:disable BlockLength
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :suites
    resources :colleges
    resources :buildings
    resources :draws
    resources :groups
    resources :memberships
    resources :rooms

    root to: 'users#index'
  end

  devise_for :users
  unauthenticated :user do
    root to: 'high_voltage/pages#show', id: 'home', as: 'landing_page'
  end
  root to: 'dashboards#show'

  resources :colleges, only: %i(new create show edit update)

  shallow do
    resources :buildings do
      resources :suites, except: :index do
        member do
          get 'merge'
          post 'merge', to: 'suites#perform_merge'
          get 'split'
          post 'split', to: 'suites#perform_split'
          post 'unmerge'
        end
        resources :rooms, except: :index
      end
    end
  end

  post 'suite_import/import', to: 'suite_imports#import', as: 'suite_import'

  resources :users do
    member do
      get 'intent', to: 'users#edit_intent', as: 'edit_intent'
      patch 'intent', to: 'users#update_intent', as: 'update_intent'
    end

    collection do
      get 'build'
    end
  end

  resources :enrollments, only: %i(new create)

  resources :draws do
    member do
      patch 'activate'
      get 'intent_report'
      post 'intent_report', to: 'draws#filter_intent_report'
      post 'reminder'
      patch 'bulk_on_campus'
      get 'students', to: 'draws#student_summary', as: 'student_summary'
      patch 'students', to: 'draws#students_update', as: 'students_update'
      get 'lottery_confirmation'
      patch 'start_lottery'
      get 'oversubscription', to: 'draws#oversubscription', as: 'oversub'
      patch 'size_lock/:size', to: 'draws#toggle_size_lock',
                               as: 'toggle_size_lock'
      patch 'lock_all_sizes'
      delete 'prune_oversub/:prune_size', to: 'draws#prune', as: 'prune'
      patch 'start_selection'
      get 'results'
    end

    resources :draw_suites, only: %i(index), as: :suites do
      collection do
        get 'edit_collection'
        patch 'update_collection'
      end
    end

    resources :lottery_assignments, only: %i(update create index) do
      collection do
        post 'automatic'
      end
    end

    resources :groups do
      member do
        post 'request', to: 'groups#request_to_join'
        put 'accept_request'
        get 'invite'
        patch 'invite', to: 'groups#send_invites', as: 'send_invites'
        put 'accept_invitation'
        put 'reject_pending'
        put 'finalize'
        put 'finalize_membership'
        put 'lock'
        put 'unlock'
        delete 'leave'
        patch 'make_drawless'
      end
      collection do
        resource :suite_assignment, only: %i(new create destroy)
      end
    end

    resource :clip, only: %i(new create)
  end

  resources :clips, only: %i(show edit update destroy)

  resources :clip_memberships, only: %i(update destroy)

  resources :groups, controller: 'drawless_groups' do
    member do
      put 'lock'
      put 'unlock'
    end
    resource :suite_assignment, only: %i(new create destroy)
    resource :room_assignment, only: %i(new create edit) do
      collection do
        get 'confirm'
      end
    end
  end

  resource :email_export, only: %i(new create)

  resources :results, only: [] do
    collection do
      get 'students'
      get 'suites'
      get 'export'
    end
  end
end

app/models/room.rb
# frozen_string_literal: true

# Model to represent the lowest-level of facility information
#
# @attr [String] number The identifier of the room. Must be unique
#   within a Suite.
# @attr [Integer] beds The number of beds within the room.
#   For common rooms, this is 0.
# @attr [Suite] suite belongs_to association for the Suite that the room is in.
# @attr [String] original_suite The number of the original suite that the room
#   was in. Is an empty string unless the room belongs to a merged suite.
class Room < ApplicationRecord
  belongs_to :suite
  has_many :users, dependent: :nullify

  validates :suite, presence: true
  validates :number, presence: true, allow_blank: false,
                     uniqueness: { scope: :suite, case_sensitive: false }
  validates :beds, presence: true,
                   numericality: { only_integer: true,
                                   greater_than_or_equal_to: 0 }

  # Suite Size Counter Cache
  after_save :update_suite_size
  after_destroy :decrement_suite_size

  # Evaluates the room type.
  #
  # @return [String] The type of room (e.g. single, common, double)
  def type
    if beds.positive?
      bedroom_type
    else
      'common'
    end
  end

  # Gets a formatted string of the room number and it's type
  #
  # @return [String] e.g. L01A (double)
  def number_with_type
    "#{number} (#{type})"
  end

  # Sets original_suite to the current suite number, unless it is already set
  #
  # @params [Hash] attrs Other attributes to update
  #
  # @return [Boolean] Whether or not the update was successful
  def store_original_suite!(**attrs)
    attrs[:original_suite] = suite.number if original_suite.blank?
    update!(attrs)
  end

  private

  def bedroom_type
    if beds > 2
      'multiple'
    else
      beds > 1 ? 'double' : 'single'
    end
  end

  def update_suite_size
    return unless saved_change_to_beds || saved_change_to_suite_id
    update_suite_size_based_on_beds if saved_change_to_beds
    update_suite_size_based_on_assignment if saved_change_to_suite_id
  end

  # rubocop:disable Rails/SkipsModelValidations
  def update_suite_size_based_on_beds
    delta = beds - beds_before_last_save
    suite.increment!(:size, delta)
  end

  def update_suite_size_based_on_assignment
    # prevent double increment on creation
    return unless suite_id_before_last_save
    # use find_by in case of deletion / nullify callback
    old_suite = Suite.find_by(id: suite_id_before_last_save)
    new_suite = Suite.find_by(id: suite_id)
    old_suite&.decrement!(:size, beds_before_last_save)
    new_suite&.increment!(:size, beds)
  end

  def decrement_suite_size
    suite.decrement!(:size, beds)
  end
  # rubocop:enable Rails/SkipsModelValidations
end

app/controllers/admin/rooms_controller.rb
# frozen_string_literal: true

module Admin
  class RoomsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Room.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Room.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

# Controller for Rooms
class RoomsController < ApplicationController
  prepend_before_action :set_room, only: %i(show edit update destroy)
  prepend_before_action :set_suite, only: %i(new create)

  def show; end

  def new
    @room = Room.new
  end

  def create
    result = Creator.new(klass: Room, params: room_params,
                         name_method: :number).create!
    @room = result[:record]
    handle_action(action: 'new', **result)
  end

  def edit; end

  def update
    result = Updater.new(object: @room, params: room_params,
                         name_method: :number).update
    @room = result[:record]
    handle_action(action: 'edit', **result)
  end

  def destroy
    result = Destroyer.new(object: @room, name_method: :number).destroy
    path = if @room.suite
             suite_path(@room.suite)
           else
             buildings_path(@building)
           end
    handle_action(path: path, **result)
  end

  private

  def authorize!
    if @room
      authorize @room
    else
      authorize Room
    end
  end

  def room_params
    params.require(:room).permit(:number, :suite_id, :beds)
  end

  def set_room
    @room = Room.find(params[:id])
  end

  def set_suite
    @suite = Suite.find(params[:suite_id])
  end
end

app/views/rooms/_form.html.erb
<%= simple_form_for [@suite, @room] do |f| %>
  <%= f.input :number %>
  <%= f.input :beds %>
  <% if @suite %>
    <%= f.hidden_field :suite_id, :value => @suite.id =%>
  <% else %>
    <%= f.input :suite_id, as: :select, collection: Suite.all, label_method: :name %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/rooms/_summary.html.erb
<table>
  <thead>
    <tr>
      <td>#</td>
      <td>Type</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% rooms.each do |room| %>
      <tr id="room-<%= room.id %>">
        <td data-role="room-number"><%= link_to room.number, room_path(room) %></td>
        <td data-role="room-type"><%= room.type.capitalize %></td>
        <td class="actions" data-role="room-actions">
          <%= link_to 'View', room_path(room), class: 'button' %>
          <% if policy(room).edit? %>
            <%= link_to 'Edit', edit_room_path(room), class: 'button' %>
          <% end %>
          <% if policy(room).destroy? %>
            <%= link_to 'Delete', room_path(room), method: :delete, data: { confirm: 'Are you sure you want to delete that room?' },
                        class: 'button alert' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/edit.html.erb
<% provide(:title, "Edit Room #{@room.number}") %>
<h1>Edit Room <%= @room.number %></h1>
<%= render "form", room: @room %>
<%= link_to 'Cancel', room_path(@room) %>

app/views/rooms/new.html.erb
<% provide(:title, 'Add Room') %>
<h1>Add Room</h1>
<%= render "form", room: @room %>
<%= link_to 'Cancel', suite_path(@suite) %>

app/views/rooms/show.html.erb
<% provide(:title, "Room #{@room.number}") %>
<h1 class="room-number">Room <%= @room.number %></h1>
<p><%= pluralize(@room.beds, 'bed') %></p>
<div>
  <% if policy(@room).edit? %>
    <%= link_to 'Edit', edit_room_path(@room), class: 'button secondary' %>
  <% end %>
  <% if policy(@room).destroy? %>
    <%= link_to 'Delete', room_path(@room), method: :delete, data: { confirm: 'Are you sure you want to delete this room?' }, class: 'button alert' %>
  <% end %>
</div>
<%= link_to 'Return to suite', suite_path(@room.suite) %>